//
//  MealsClient.swift
//  WBChat
//
//  Created by Александр on 11.08.2024.
//

import Foundation
import OpenAPIRuntime
import OpenAPIURLSession

struct MockClient: APIProtocol {
    func filterByCategory(_ input: Operations.filterByCategory.Input) async throws -> Operations.filterByCategory.Output {
        let meals = Optional([
            WBChat.Components.Schemas.Meal(idMeal: "52874", strMeal: "Beef and Mustard Pie", strCategory: nil, strArea: nil, strInstructions: nil, strMealThumb: "https://www.themealdb.com/images/media/meals/sytuqu1511553755.jpg", strTags: nil, strYoutube: nil),
            WBChat.Components.Schemas.Meal(idMeal: "52878", strMeal: "Beef and Oyster pie", strCategory: nil, strArea: nil, strInstructions: nil, strMealThumb: "https://www.themealdb.com/images/media/meals/wrssvt1511556563.jpg", strTags: nil, strYoutube: nil),
            WBChat.Components.Schemas.Meal(idMeal: "53071", strMeal: "Beef Asado", strCategory: nil, strArea: nil, strInstructions: nil, strMealThumb: "https://www.themealdb.com/images/media/meals/pkopc31683207947.jpg", strTags: nil, strYoutube: nil),
            WBChat.Components.Schemas.Meal(idMeal: "52997", strMeal: "Beef Banh Mi Bowls with Sriracha Mayo, Carrot & Pickled Cucumber", strCategory: nil, strArea: nil, strInstructions: nil, strMealThumb: "https://www.themealdb.com/images/media/meals/z0ageb1583189517.jpg", strTags: nil, strYoutube: nil),
            WBChat.Components.Schemas.Meal(idMeal: "52904", strMeal: "Beef Bourguignon", strCategory: nil, strArea: nil, strInstructions: nil, strMealThumb: "https://www.themealdb.com/images/media/meals/vtqxtu1511784197.jpg", strTags: nil, strYoutube: nil),
            WBChat.Components.Schemas.Meal(idMeal: "52812", strMeal: "Beef Brisket Pot Roast", strCategory: nil, strArea: nil, strInstructions: nil, strMealThumb: "https://www.themealdb.com/images/media/meals/ursuup1487348423.jpg", strTags: nil, strYoutube: nil),
            WBChat.Components.Schemas.Meal(idMeal: "53070", strMeal: "Beef Caldereta", strCategory: nil, strArea: nil, strInstructions: nil, strMealThumb: "https://www.themealdb.com/images/media/meals/41cxjh1683207682.jpg", strTags: nil, strYoutube: nil),
            WBChat.Components.Schemas.Meal(idMeal: "52873", strMeal: "Beef Dumpling Stew", strCategory: nil, strArea: nil, strInstructions: nil, strMealThumb: "https://www.themealdb.com/images/media/meals/uyqrrv1511553350.jpg", strTags: nil, strYoutube: nil),
            WBChat.Components.Schemas.Meal(idMeal: "52952", strMeal: "Beef Lo Mein", strCategory: nil, strArea: nil, strInstructions: nil, strMealThumb: "https://www.themealdb.com/images/media/meals/1529444830.jpg", strTags: nil, strYoutube: nil),
            WBChat.Components.Schemas.Meal(idMeal: "53068", strMeal: "Beef Mechado", strCategory: nil, strArea: nil, strInstructions: nil, strMealThumb: "https://www.themealdb.com/images/media/meals/cgl60b1683206581.jpg", strTags: nil, strYoutube: nil)])
         return .ok(Operations.filterByCategory.Output.Ok(body: .json(.init(meals: meals))))
    }
    
    func getAllCategories(_ input: Operations.getAllCategories.Input) async throws -> Operations.getAllCategories.Output {
        let categories =  [
            MealCategory(idCategory: "1", strCategory: "Beef", strCategoryThumb: "https://www.themealdb.com/images/category/beef.png", strCategoryDescription: Optional("Beef is the culinary name for meat from cattle, particularly skeletal muscle. Humans have been eating beef since prehistoric times.[1] Beef is a source of high-quality protein and essential nutrients.[2]")),
            MealCategory(idCategory: "2", strCategory: "Chicken", strCategoryThumb: "https://www.themealdb.com/images/category/chicken.png", strCategoryDescription: Optional("Chicken is a type of domesticated fowl, a subspecies of the red junglefowl. It is one of the most common and widespread domestic animals, with a total population of more than 19 billion as of 2011.[1] Humans commonly keep chickens as a source of food (consuming both their meat and eggs) and, more rarely, as pets.")),
            MealCategory(idCategory: "3", strCategory: "Dessert", strCategoryThumb: "https://www.themealdb.com/images/category/dessert.png", strCategoryDescription: Optional("Dessert is a course that concludes a meal. The course usually consists of sweet foods, such as confections dishes or fruit, and possibly a beverage such as dessert wine or liqueur, however in the United States it may include coffee, cheeses, nuts, or other savory items regarded as a separate course elsewhere. In some parts of the world, such as much of central and western Africa, and most parts of China, there is no tradition of a dessert course to conclude a meal.\r\n\r\nThe term dessert can apply to many confections, such as biscuits, cakes, cookies, custards, gelatins, ice creams, pastries, pies, puddings, and sweet soups, and tarts. Fruit is also commonly found in dessert courses because of its naturally occurring sweetness. Some cultures sweeten foods that are more commonly savory to create desserts.")),
            MealCategory(idCategory: "4", strCategory: "Lamb", strCategoryThumb: "https://www.themealdb.com/images/category/lamb.png", strCategoryDescription: Optional("Lamb, hogget, and mutton are the meat of domestic sheep (species Ovis aries) at different ages.\r\n\r\nA sheep in its first year is called a lamb, and its meat is also called lamb. The meat of a juvenile sheep older than one year is hogget; outside the USA this is also a term for the living animal. The meat of an adult sheep is mutton, a term only used for the meat, not the living animals. The term mutton is almost always used to refer to goat meat in the Indian subcontinent.\r\n\r\n")),
            MealCategory(idCategory: "5", strCategory: "Miscellaneous", strCategoryThumb: "https://www.themealdb.com/images/category/miscellaneous.png", strCategoryDescription: Optional("General foods that don\'t fit into another category")),
            MealCategory(idCategory: "6", strCategory: "Pasta", strCategoryThumb: "https://www.themealdb.com/images/category/pasta.png", strCategoryDescription: Optional("Pasta is a staple food of traditional Italian cuisine, with the first reference dating to 1154 in Sicily.\r\n\r\nAlso commonly used to refer to the variety of pasta dishes, pasta is typically a noodle made from an unleavened dough of a durum wheat flour mixed with water or eggs and formed into sheets or various shapes, then cooked by boiling or baking. As an alternative for those wanting a different taste, or who need to avoid products containing gluten, some pastas can be made using rice flour in place of wheat.[3][4] Pastas may be divided into two broad categories, dried (pasta secca) and fresh (pasta fresca).")),
            MealCategory(idCategory: "7", strCategory: "Pork", strCategoryThumb: "https://www.themealdb.com/images/category/pork.png", strCategoryDescription: Optional("Pork is the culinary name for meat from a domestic pig (Sus scrofa domesticus). It is the most commonly consumed meat worldwide,[1] with evidence of pig husbandry dating back to 5000 BC. Pork is eaten both freshly cooked and preserved. Curing extends the shelf life of the pork products. Ham, smoked pork, gammon, bacon and sausage are examples of preserved pork. Charcuterie is the branch of cooking devoted to prepared meat products, many from pork.\r\n\r\nPork is the most popular meat in Eastern and Southeastern Asia, and is also very common in the Western world, especially in Central Europe. It is highly prized in Asian cuisines for its fat content and pleasant texture. Consumption of pork is forbidden by Jewish and Muslim dietary law, a taboo that is deeply rooted in tradition, with several suggested possible causes. The sale of pork is limited in Israel and illegal in certain Muslim countries.")),
            ]
        return .ok(Operations.getAllCategories.Output.Ok(body: .json(.init(categories: categories))))
    }
    
    func getMealById(_ input: Operations.getMealById.Input) async throws -> Operations.getMealById.Output {
        let meals = [WBChat.Components.Schemas.Meal(idMeal: "52995", strMeal: "BBQ Pork Sloppy Joes", strCategory: Optional("Pork"), strArea: Optional("American"), strInstructions: Optional("1\r\n\r\nPreheat oven to 450 degrees. Wash and dry all produce. Cut sweet potatoes into ½-inch-thick wedges. Toss on a baking sheet with a drizzle of oil, salt, and pepper. Roast until browned and tender, 20-25 minutes.\r\n\r\n2\r\n\r\nMeanwhile, halve and peel onion. Slice as thinly as possible until you have ¼ cup (½ cup for 4 servings); finely chop remaining onion. Peel and finely chop garlic. Halve lime; squeeze juice into a small bowl. Halve buns. Add 1 TBSP butter (2 TBSP for 4) to a separate small microwave-safe bowl; microwave until melted, 30 seconds. Brush onto cut sides of buns.\r\n\r\n3\r\n\r\nTo bowl with lime juice, add sliced onion, ¼ tsp sugar (½ tsp for 4 servings), and a pinch of salt. Stir to combine; set aside to quick-pickle.\r\n\r\n4\r\n\r\nHeat a drizzle of oil in a large pan over medium-high heat. Add chopped onion and season with salt and pepper. Cook, stirring, until softened, 4-5 minutes. Add garlic and cook until fragrant, 30 seconds more. Add pork and season with salt and pepper. Cook, breaking up meat into pieces, until browned and cooked through, 4-6 minutes.\r\n\r\n5\r\n\r\nWhile pork cooks, in a third small bowl, combine BBQ sauce, pickling liquid from onion, 3 TBSP ketchup (6 TBSP for 4 servings), ½ tsp sugar (1 tsp for 4), and ¼ cup water (⅓ cup for 4). Once pork is cooked through, add BBQ sauce mixture to pan. Cook, stirring, until sauce is thickened, 2-3 minutes. Taste and season with salt and pepper.\r\n\r\n6\r\n\r\nMeanwhile, toast buns in oven or toaster oven until golden, 3-5 minutes. Divide toasted buns between plates and fill with as much BBQ pork as you’d like. Top with pickled onion and hot sauce. Serve with sweet potato wedges on the side."), strMealThumb: "https://www.themealdb.com/images/media/meals/atd5sh1583188467.jpg", strTags: nil, strYoutube: Optional(""))]
         return .ok(Operations.getMealById.Output.Ok(body: .json(.init(meals: meals))))
    }
    
    func searchMealByName(_ input: Operations.searchMealByName.Input) async throws -> Operations.searchMealByName.Output {
        let meals = Optional([WBChat.Components.Schemas.Meal(idMeal: "52995", strMeal: "BBQ Pork Sloppy Joes", strCategory: Optional("Pork"), strArea: Optional("American"), strInstructions: Optional("1\r\n\r\nPreheat oven to 450 degrees. Wash and dry all produce. Cut sweet potatoes into ½-inch-thick wedges. Toss on a baking sheet with a drizzle of oil, salt, and pepper. Roast until browned and tender, 20-25 minutes.\r\n\r\n2\r\n\r\nMeanwhile, halve and peel onion. Slice as thinly as possible until you have ¼ cup (½ cup for 4 servings); finely chop remaining onion. Peel and finely chop garlic. Halve lime; squeeze juice into a small bowl. Halve buns. Add 1 TBSP butter (2 TBSP for 4) to a separate small microwave-safe bowl; microwave until melted, 30 seconds. Brush onto cut sides of buns.\r\n\r\n3\r\n\r\nTo bowl with lime juice, add sliced onion, ¼ tsp sugar (½ tsp for 4 servings), and a pinch of salt. Stir to combine; set aside to quick-pickle.\r\n\r\n4\r\n\r\nHeat a drizzle of oil in a large pan over medium-high heat. Add chopped onion and season with salt and pepper. Cook, stirring, until softened, 4-5 minutes. Add garlic and cook until fragrant, 30 seconds more. Add pork and season with salt and pepper. Cook, breaking up meat into pieces, until browned and cooked through, 4-6 minutes.\r\n\r\n5\r\n\r\nWhile pork cooks, in a third small bowl, combine BBQ sauce, pickling liquid from onion, 3 TBSP ketchup (6 TBSP for 4 servings), ½ tsp sugar (1 tsp for 4), and ¼ cup water (⅓ cup for 4). Once pork is cooked through, add BBQ sauce mixture to pan. Cook, stirring, until sauce is thickened, 2-3 minutes. Taste and season with salt and pepper.\r\n\r\n6\r\n\r\nMeanwhile, toast buns in oven or toaster oven until golden, 3-5 minutes. Divide toasted buns between plates and fill with as much BBQ pork as you’d like. Top with pickled onion and hot sauce. Serve with sweet potato wedges on the side."), strMealThumb: "https://www.themealdb.com/images/media/meals/atd5sh1583188467.jpg", strTags: nil, strYoutube: Optional(""))])
         return .ok(Operations.searchMealByName.Output.Ok(body: .json(.init(meals: meals))))
    }
    
    func getRandomMeal(_ input: Operations.getRandomMeal.Input) async throws -> Operations.getRandomMeal.Output {
       let meals = [WBChat.Components.Schemas.Meal(idMeal: "52995", strMeal: "BBQ Pork Sloppy Joes", strCategory: Optional("Pork"), strArea: Optional("American"), strInstructions: Optional("1\r\n\r\nPreheat oven to 450 degrees. Wash and dry all produce. Cut sweet potatoes into ½-inch-thick wedges. Toss on a baking sheet with a drizzle of oil, salt, and pepper. Roast until browned and tender, 20-25 minutes.\r\n\r\n2\r\n\r\nMeanwhile, halve and peel onion. Slice as thinly as possible until you have ¼ cup (½ cup for 4 servings); finely chop remaining onion. Peel and finely chop garlic. Halve lime; squeeze juice into a small bowl. Halve buns. Add 1 TBSP butter (2 TBSP for 4) to a separate small microwave-safe bowl; microwave until melted, 30 seconds. Brush onto cut sides of buns.\r\n\r\n3\r\n\r\nTo bowl with lime juice, add sliced onion, ¼ tsp sugar (½ tsp for 4 servings), and a pinch of salt. Stir to combine; set aside to quick-pickle.\r\n\r\n4\r\n\r\nHeat a drizzle of oil in a large pan over medium-high heat. Add chopped onion and season with salt and pepper. Cook, stirring, until softened, 4-5 minutes. Add garlic and cook until fragrant, 30 seconds more. Add pork and season with salt and pepper. Cook, breaking up meat into pieces, until browned and cooked through, 4-6 minutes.\r\n\r\n5\r\n\r\nWhile pork cooks, in a third small bowl, combine BBQ sauce, pickling liquid from onion, 3 TBSP ketchup (6 TBSP for 4 servings), ½ tsp sugar (1 tsp for 4), and ¼ cup water (⅓ cup for 4). Once pork is cooked through, add BBQ sauce mixture to pan. Cook, stirring, until sauce is thickened, 2-3 minutes. Taste and season with salt and pepper.\r\n\r\n6\r\n\r\nMeanwhile, toast buns in oven or toaster oven until golden, 3-5 minutes. Divide toasted buns between plates and fill with as much BBQ pork as you’d like. Top with pickled onion and hot sauce. Serve with sweet potato wedges on the side."), strMealThumb: "https://www.themealdb.com/images/media/meals/atd5sh1583188467.jpg", strTags: nil, strYoutube: Optional(""))]
        return .ok(Operations.getRandomMeal.Output.Ok(body: .json(.init(meals: meals))))
    }
}
